name: flutter_application_1
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  esig_utils: ^5.4.1
  loading_empty_error: ^3.4.4
  one_context: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.0+1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

assets:
  - assets/userpicture.png
fonts:
  - family: Metropolis
    fonts:
      - asset: assets/fonts/Metropolis-Black.otf
      - asset: assets/fonts/Metropolis-Bold.otf
      - asset: assets/fonts/Metropolis-ExtraBold.otf
      - asset: assets/fonts/Metropolis-ExtraLight.otf
      - asset: assets/fonts/Metropolis-Light.otf
      - asset: assets/fonts/Metropolis-Medium.otf
      - asset: assets/fonts/Metropolis-Regular.otf
      - asset: assets/fonts/Metropolis-SemiBold.otf
      - asset: assets/fonts/Metropolis-Thin.otf
